#cloud-config
users:
  - name: ${ssh_username}
    ssh-authorized-keys:
      - ssh-rsa ${public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

packages:
  - tree
runcmd:
  - echo "Start TKG create."
  - su ${ssh_username} -c "tanzu mc create --file /home/${ssh_username}/tanzu-install/mgmtcluster.yaml"